/**
 * ledger.js – Fix Ledger storage (Phase 1)
 * Persists fix cards to localStorage.  F8, F9.
 * No DOM dependencies – storage only.
 */

const LEDGER_KEY = 'tb:ledger:v1';
const NAME_KEY   = 'tb:name:v1';

/**
 * @typedef {Object} FixCard
 * @property {string}   id         – random UUID
 * @property {string}   fp         – fingerprint
 * @property {string}   fam        – language family
 * @property {string}   cls        – error class
 * @property {string[]} kw         – keywords (up to 8)
 * @property {Uint8Array|number[]} mh – MinHash (stored as array)
 * @property {number}   solvedAt   – unix seconds
 * @property {string}   note       – helper's written/spoken fix note
 * @property {boolean}  confirmed  – true when asker tapped Solved
 * @property {boolean}  synthetic  – true for seed data
 */

// ── Read / Write ──────────────────────────────────────────────────────────────
function readAll() {
  try {
    const raw = localStorage.getItem(LEDGER_KEY);
    if (!raw) return [];
    const entries = JSON.parse(raw);
    // Re-hydrate mh as Uint8Array
    return entries.map(e => ({
      ...e,
      mh: new Uint8Array(e.mh),
    }));
  } catch {
    return [];
  }
}

function writeAll(entries) {
  // Uint8Array is not JSON-serialisable, convert to plain array
  const serialisable = entries.map(e => ({
    ...e,
    mh: Array.from(e.mh),
  }));
  localStorage.setItem(LEDGER_KEY, JSON.stringify(serialisable));
}

// ── Public API ────────────────────────────────────────────────────────────────
export function getAllEntries() {
  return readAll();
}

/**
 * Add a new fix card to the ledger.
 * @param {Omit<FixCard,'id'|'solvedAt'>} card
 * @returns {FixCard}
 */
export function addEntry(card) {
  const entries = readAll();
  const full = {
    ...card,
    id:       crypto.randomUUID(),
    solvedAt: Math.floor(Date.now() / 1000),
  };
  entries.unshift(full);
  writeAll(entries);
  return full;
}

/**
 * Mark an existing entry as confirmed (asker tapped Solved).
 * @param {string} id
 */
export function confirmEntry(id) {
  const entries = readAll();
  const idx = entries.findIndex(e => e.id === id);
  if (idx !== -1) {
    entries[idx].confirmed = true;
    writeAll(entries);
  }
}

/**
 * Delete an entry by id.
 * @param {string} id
 */
export function deleteEntry(id) {
  const entries = readAll().filter(e => e.id !== id);
  writeAll(entries);
}

/** Clear the ledger completely (test helper only). */
export function clearLedger() {
  localStorage.removeItem(LEDGER_KEY);
}

// ── Seed synthetic data ───────────────────────────────────────────────────────
/**
 * Seed from ledger-seed.json if the ledger is empty.
 * Marks all seeded entries as synthetic.
 * @param {Object[]} seedData – parsed ledger-seed.json
 */
export function seedIfEmpty(seedData) {
  if (readAll().length > 0) return;
  const entries = seedData.map(s => ({
    ...s,
    mh:       new Uint8Array(s.mh ?? new Array(32).fill(0)),
    id:       s.id ?? crypto.randomUUID(),
    synthetic: true,
  }));
  writeAll(entries);
}

// ── Helper name ───────────────────────────────────────────────────────────────
export function getHelperName()        { return localStorage.getItem(NAME_KEY) ?? ''; }
export function setHelperName(name)    { localStorage.setItem(NAME_KEY, name.slice(0, 32)); }

// ── Export as markdown ────────────────────────────────────────────────────────
/**
 * Generate a markdown fix card string.
 * @param {FixCard} card
 * @returns {string}
 */
export function toMarkdown(card) {
  const date = new Date(card.solvedAt * 1000).toISOString().slice(0, 10);
  const syntheticNote = card.synthetic ? '\n> ⚠️ This is a synthetic seed entry used for demonstration.\n' : '';
  return `# Fix card – ${card.cls || card.fam} (${card.fp})

**Family:** ${card.fam}  
**Error class:** ${card.cls || '—'}  
**Keywords:** ${card.kw.join(', ')}  
**Flag code:** (see app)  
**Solved at:** ${date}  
**Confirmed by asker:** ${card.confirmed ? 'Yes' : 'No'}  
${syntheticNote}
## Fix note

${card.note || '(No note recorded.)'}

---
*Generated by Tracebeam – Phase 1 prototype. Team Lagnarok, iQOO Hackathon 2026.*
`;
}
